Machine learning
Machine Learning is a method of teaching computers to learn from data and improve their performance automatically. What is Machine Learning?
Machine Learning (ML) is a branch of Artificial Intelligence (AI) that enables computers to learn from data and improve their performance without being explicitly programmed.

Definition:

"Machine Learning is the ability of a computer system to learn from data and make predictions or decisions without being explicitly programmed."

Types of Machine Learning

Supervised Learning
In Supervised Learning, the model is trained using labeled data, where both input and output are known.

Features: Uses labeled data. Predicts outcomes based on learned patterns. Examples: Email Spam Detection House Price Prediction Student Performance Prediction Common Algorithms: Linear Regression Logistic Regression Decision Tree Random Forest Example:

A model learns the relationship between study hours and exam marks to predict future results.

Unsupervised Learning
In Unsupervised Learning, the model is trained using unlabeled data.

Features: No predefined output. Finds hidden patterns and relationships in data. Examples: Customer Segmentation Recommendation Systems Market Basket Analysis Common Algorithms: K-Means Clustering Hierarchical Clustering Apriori Algorithm Example:

An e-commerce company groups customers based on similar purchasing behavior.

semi supervised
Semi-Supervised Learning is a combination of Supervised Learning and Unsupervised Learning.

It uses:

A small amount of labeled data A large amount of unlabeled data

This approach is useful when labeling data is expensive or time-consuming.

Definition:

"Semi-Supervised Learning is a machine learning technique that trains a model using both labeled and unlabeled data."

Example:

Suppose you have:

1000 images of animals Only 100 images are labeled (cat, dog, etc.) 900 images are unlabeled

The model uses the labeled images to learn and the unlabeled images to improve its understanding and accuracy.

Applications: Image Classification Speech Recognition Medical Diagnosis Web Content Classification Advantages:

✅ Requires less labeled data ✅ More accurate than purely unsupervised learning ✅ Reduces the cost of data labeling

Example in Real Life:

A photo app may have a few labeled pictures of cats and dogs, while thousands of unlabeled photos are available. The model learns from both to improve its classification performance.

Reinforcement Learning
In Reinforcement Learning, an agent learns by interacting with its environment and receiving rewards or penalties.

Features: Learns through trial and error. Goal is to maximize rewards. Examples: Self-Driving Cars Robotics Game Playing (Chess, AlphaGo) Example:

A robot learns to navigate a room by receiving rewards for correct actions and penalties for mistakes.

Comparison of Machine Learning Types Feature Supervised Learning Unsupervised Learning Reinforcement Learning Data Type Labeled Data Unlabeled Data Reward-Based Data Output Known Yes No No Goal Prediction Pattern Discovery Decision Making Example Spam Detection Customer Segmentation Self-Driving Car

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv("clean_bike_data.csv")

In [30]:
df

,Unnamed: 0,bike_name,price,city,kms_driven,owner,age,power,brand
0,0,1.0,35000.0,1.0,17654.0,1,3.0,110.0,1
1,1,2.0,119900.0,2.0,11000.0,1,4.0,350.0,2
2,2,3.0,600000.0,2.0,110.0,1,8.0,675.0,3
3,3,4.0,65000.0,3.0,16329.0,1,4.0,180.0,1
4,4,5.0,80000.0,3.0,10000.0,1,3.0,150.0,4
...,...,...,...,...,...,...,...,...,...
364,9205,6.0,31000.0,2.0,58000.0,1,10.0,150.0,4
365,9235,2.0,150000.0,3.0,5400.0,1,8.0,350.0,2
366,9241,10.0,140000.0,2.0,8500.0,1,5.0,500.0,2
367,9245,2.0,105000.0,2.0,14779.0,1,4.0,350.0,2
368,9362,20.0,25000.0,2.0,48587.0,1,8.0,150.0,6

In [31]:
df.drop("Unnamed: 0",axis = 1,inplace=True)

In [32]:
x=df.drop("price",axis = 1)
y=df[["price"]]

In [33]:
x

     bike_name  city  kms_driven  owner   age  power  brand
0          1.0   1.0     17654.0      1   3.0  110.0      1
1          2.0   2.0     11000.0      1   4.0  350.0      2
2          3.0   2.0       110.0      1   8.0  675.0      3
3          4.0   3.0     16329.0      1   4.0  180.0      1
4          5.0   3.0     10000.0      1   3.0  150.0      4
..         ...   ...         ...    ...   ...    ...    ...
364        6.0   2.0     58000.0      1  10.0  150.0      4
365        2.0   3.0      5400.0      1   8.0  350.0      2
366       10.0   2.0      8500.0      1   5.0  500.0      2
367        2.0   2.0     14779.0      1   4.0  350.0      2
368       20.0   2.0     48587.0      1   8.0  150.0      6

[369 rows x 7 columns]

In [34]:
y

        price
0     35000.0
1    119900.0
2    600000.0
3     65000.0
4     80000.0
..        ...
364   31000.0
365  150000.0
366  140000.0
367  105000.0
368   25000.0

[369 rows x 1 columns]

In [37]:
#! pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.4.6)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   --- ------------------------------------ 0.8/8.3 MB 7.9 MB/s eta 0:00:01
   ------------------ --------------------- 3.9/8.3 MB 15.6 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 17.5 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 15.7 MB/s  0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Downloading scipy-1.17.1-cp314-cp314-win_amd64.whl (37.3 MB)
   ---------------------------------------- 0.0/37.3 MB ? eta -:--:--
   --- ------------------------------------ 2.9/37.3 MB 24.4 MB/s eta 0:00:02
   -------- ------------------------------- 7.6/37.3 MB 17.5 MB/s eta 0:00:02
   ---------- ----------------------------- 9.7/37.3 MB 16.9 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   ------------- -------------------------- 12.6/37.3 MB 15.4 MB/s eta 0:00:02
   -------------- ------------------------- 13.4/37.3 MB 2.3 MB/s eta 0:00:11
   -------------- ------------------------- 13.9/37.3 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 14.2/37.3 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 14.4/37.3 MB 2.3 MB/s eta 0:00:11
   --------------- ------------------------ 14.7/37.3 MB 2.3 MB/s eta 0:00:10
   ---------------- ----------------------- 15.2/37.3 MB 2.2 MB/s eta 0:00:10
   ---------------- ----------------------- 15.5/37.3 MB 2.2 MB/s eta 0:00:10
   ---------------- ----------------------- 15.7/37.3 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.3/37.3 MB 2.2 MB/s eta 0:00:10
   ----------------- ---------------------- 16.5/37.3 MB 2.2 MB/s eta 0:00:10
   ------------------ --------------------- 17.0/37.3 MB 2.2 MB/s eta 0:00:10
   ------------------ --------------------- 17.3/37.3 MB 2.1 MB/s eta 0:00:10
   ------------------- -------------------- 17.8/37.3 MB 2.1 MB/s eta 0:00:10
   ------------------- -------------------- 18.1/37.3 MB 2.1 MB/s eta 0:00:09
   ------------------- -------------------- 18.6/37.3 MB 2.1 MB/s eta 0:00:09
   -------------------- ------------------- 18.9/37.3 MB 2.1 MB/s eta 0:00:09
   -------------------- ------------------- 19.4/37.3 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 19.7/37.3 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 19.9/37.3 MB 2.1 MB/s eta 0:00:09
   --------------------- ------------------ 20.4/37.3 MB 2.1 MB/s eta 0:00:09
   ---------------------- ----------------- 21.0/37.3 MB 2.1 MB/s eta 0:00:08
   ----------------------- ---------------- 21.5/37.3 MB 2.1 MB/s eta 0:00:08
   ----------------------- ---------------- 21.8/37.3 MB 2.1 MB/s eta 0:00:08
   ----------------------- ---------------- 22.3/37.3 MB 2.1 MB/s eta 0:00:08
   ------------------------ --------------- 22.8/37.3 MB 2.1 MB/s eta 0:00:07
   ------------------------ --------------- 23.1/37.3 MB 2.1 MB/s eta 0:00:07
   ------------------------- -------------- 23.6/37.3 MB 2.1 MB/s eta 0:00:07
   ------------------------- -------------- 23.9/37.3 MB 2.1 MB/s eta 0:00:07
   -------------------------- ------------- 24.4/37.3 MB 2.1 MB/s eta 0:00:07
   -------------------------- ------------- 24.9/37.3 MB 2.1 MB/s eta 0:00:06
   --------------------------- ------------ 25.4/37.3 MB 2.1 MB/s eta 0:00:06
   --------------------------- ------------ 26.0/37.3 MB 2.1 MB/s eta 0:00:06
   ---------------------------- ----------- 26.5/37.3 MB 2.1 MB/s eta 0:00:06
   ---------------------------- ----------- 27.0/37.3 MB 2.1 MB/s eta 0:00:05
   ----------------------------- ---------- 27.5/37.3 MB 2.1 MB/s eta 0:00:05
   ------------------------------ --------- 28.0/37.3 MB 2.1 MB/s eta 0:00:05
   ------------------------------ --------- 28.6/37.3 MB 2.1 MB/s eta 0:00:05
   ------------------------------- -------- 29.1/37.3 MB 2.1 MB/s eta 0:00:04
   ------------------------------- -------- 29.6/37.3 MB 2.1 MB/s eta 0:00:04
   -------------------------------- ------- 30.1/37.3 MB 2.2 MB/s eta 0:00:04
   --------------------------------- ------ 30.9/37.3 MB 2.2 MB/s eta 0:00:03
   --------------------------------- ------ 31.5/37.3 MB 2.2 MB/s eta 0:00:03
   ---------------------------------- ----- 32.0/37.3 MB 2.2 MB/s eta 0:00:03
   ---------------------------------- ----- 32.5/37.3 MB 2.2 MB/s eta 0:00:03
   ----------------------------------- ---- 33.0/37.3 MB 2.2 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/37.3 MB 2.2 MB/s eta 0:00:02
   ------------------------------------ --- 34.3/37.3 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 34.9/37.3 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 35.1/37.3 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 35.7/37.3 MB 2.2 MB/s eta 0:00:01
   -------------------------------------- - 35.9/37.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  36.4/37.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  37.0/37.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  37.2/37.3 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 37.3/37.3 MB 2.2 MB/s  0:00:17
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, scikit-learn

   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   -------- ------------------------------- 1/5 [scipy]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ---------------- ----------------------- 2/5 [narwhals]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]
   ------------------------ --------------- 3/5 [joblib]

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x,y, random_state =42, test_size = 0.2)

In [39]:
x_train.shape ,y_train.shape ,x_test.shape , y_test.shape

((295, 7), (295, 1), (74, 7), (74, 1))

In [40]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train , y_train)

LinearRegression()

In [41]:
bike_1 = lr.predict([[1.0,	1.0	,17654.0,	1	,3.0,	110.0,	1]])
bike_1

c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[30718.95196361]])

In [42]:
print(lr.score(x_train, y_train))
print(lr.score(x_test, y_test))

0.6845723012426541
0.7150694585150776

In [43]:
import joblib

In [44]:
joblib.dump(lr , "model.lb")

['model.lb']

In [45]:
model = joblib.load("model.lb")

In [46]:
model.predict([[2.0	,2.0,	11000.0,	1,	4.0,	350.0,	2]])

c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[123088.04339355]])

In [47]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
dtr = DecisionTreeRegressor()

In [48]:
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [49]:
dtr.fit(x_train , y_train)

DecisionTreeRegressor()

In [50]:
print(dtr.score(x_train,y_train))
print(dtr.score(x_test,y_test))

0.9997423278406229
0.7076231624161425

In [51]:
x_train

     bike_name  city  kms_driven  owner  age  power  brand
344        2.0   4.0     29639.0      1  5.0  350.0      2
192        6.0   6.0     40000.0      2  9.0  150.0      4
75         2.0   2.0      7850.0      1  4.0  350.0      2
84         6.0   9.0     31085.0      2  8.0  150.0      4
357        2.0   3.0      6410.0      1  4.0  350.0      2
..         ...   ...         ...    ...  ...    ...    ...
71         2.0   2.0      8000.0      1  6.0  350.0      2
106        6.0   2.0     18000.0      1  8.0  150.0      4
270        2.0   2.0      5580.0      1  4.0  350.0      2
348        6.0   9.0     31586.0      1  8.0  150.0      4
102        2.0   2.0     29299.0      1  4.0  350.0      2

[295 rows x 7 columns]

In [52]:
y_train

        price
344  110000.0
192   22500.0
75   115000.0
84    23000.0
357  150000.0
..        ...
71   180000.0
106   40000.0
270  130000.0
348   28000.0
102  111500.0

[295 rows x 1 columns]

In [53]:
y_train

        price
344  110000.0
192   22500.0
75   115000.0
84    23000.0
357  150000.0
..        ...
71   180000.0
106   40000.0
270  130000.0
348   28000.0
102  111500.0

[295 rows x 1 columns]

In [54]:
x_test

     bike_name  city  kms_driven  owner  age  power  brand
326        2.0   2.0     15000.0      1  7.0  350.0      2
33         2.0   3.0      7000.0      1  3.0  350.0      2
15         2.0   2.0     11000.0      1  6.0  350.0      2
345        4.0   3.0     13608.0      1  5.0  180.0      1
57         2.0   2.0      7500.0      1  4.0  350.0      2
..         ...   ...         ...    ...  ...    ...    ...
82         2.0   7.0      2476.0      1  5.0  350.0      2
94         4.0   2.0      2400.0      1  3.0  180.0      1
195        6.0   3.0     23000.0      1  5.0  150.0      4
310        6.0   4.0     22917.0      1  9.0  150.0      4
292        2.0   3.0     61129.0      1  5.0  350.0      2

[74 rows x 7 columns]

In [55]:
y_test

        price
326  107000.0
33   143000.0
15    92500.0
345   60000.0
57   114000.0
..        ...
82   129200.0
94    60000.0
195   66000.0
310   25000.0
292   90000.0

[74 rows x 1 columns]

In [56]:
dtr.predict([[2.0,	2.0,	15000.0	,1,	7.0	,350.0,	2]])

c:\Users\Pc\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

array([87000.])